-- AlterTable
ALTER TABLE `UserProgress` ADD COLUMN `currentLevel` INT NOT NULL DEFAULT 1,
ADD COLUMN `totalScore` INT NOT NULL DEFAULT 0,
ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'Idle',
ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);